apiVersion: v1
kind: Service
metadata: 
    name: django-cluster-ip-service
spec: 
    type: ClusterIP            
    selector: 
        app: python
    ports:
        - port: 8002
          targetPort: 8003 
