apiVersion: v1 
kind: Pod 
metadata: 
    name: django-pod
    labels: 
        app: python
spec:
    containers:
    - name: django-container 
      image: karanshreds/kubernetes_django1
      ports: 
         - containerPort: 8003
 
