---
kind: Service 
apiVersion: v1
metadata: 
  name: django-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec: 
  type: LoadBalancer
  selector: 
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
